version: '3.7'

services:
  
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=root

  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080
