version: '3.7'

services:
  # node:
  #   build: .
  #   restart: always
  #   ports:
  #     - "9000:9000"
  #   tty: true
  #   volumes:
  #     - .:/usr/src/app

  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=node
      - MYSQL_USER=db
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root

  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080
